#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname "$0")/.."

help=$(deny-self-approve help-all)

echo "# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$help" > USAGE.md
