#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname "$0")/.."

out=$(deny-self-approve --help)

{
  echo "# Usage"
  echo ""
  echo "<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->"
  echo '```console'
  echo "$out"
  echo '```'
} > USAGE.md
