#!/usr/bin/env bash

set -eu
set -o pipefail

cd "$(dirname "$0")/.."

command_console() {
  echo '```console'
  echo "$ $*"
  "$@"
  echo '```'
}

commands() {
  for cmd in validate dismiss version; do
    echo "
## deny-self-approve $cmd

$(command_console deny-self-approve help $cmd)"
  done
}

echo "# Usage

<!-- This is generated by scripts/generate-usage.sh. Don't edit this file directly. -->

$(command_console deny-self-approve help)
$(commands)" > USAGE.md
